# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hdcp4.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(825, 826)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 771, 631))
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem = QtGui.QSpacerItem(20, 33, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.macEdit = QtGui.QLineEdit(self.tab)
        self.macEdit.setObjectName(_fromUtf8("macEdit"))
        self.horizontalLayout.addWidget(self.macEdit)
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_9 = QtGui.QPushButton(self.tab)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_2.addWidget(self.pushButton_9)
        self.file_edit = QtGui.QLineEdit(self.tab)
        self.file_edit.setObjectName(_fromUtf8("file_edit"))
        self.horizontalLayout_2.addWidget(self.file_edit)
        self.pushButton_2 = QtGui.QPushButton(self.tab)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(20, 33, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(50, -1, -1, -1)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_69 = QtGui.QLabel(self.tab)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.horizontalLayout_9.addWidget(self.label_69)
        self.radioButton = QtGui.QRadioButton(self.tab)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.buttonGroup_7 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_7.setObjectName(_fromUtf8("buttonGroup_7"))
        self.buttonGroup_7.addButton(self.radioButton)
        self.horizontalLayout_9.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.tab)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.buttonGroup_7.addButton(self.radioButton_2)
        self.horizontalLayout_9.addWidget(self.radioButton_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        spacerItem2 = QtGui.QSpacerItem(20, 33, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(50, -1, 50, -1)
        self.gridLayout.setHorizontalSpacing(100)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_1x_rx_total = QtGui.QLabel(self.tab)
        self.label_1x_rx_total.setObjectName(_fromUtf8("label_1x_rx_total"))
        self.gridLayout.addWidget(self.label_1x_rx_total, 0, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_1x_rx_left = QtGui.QLabel(self.tab)
        self.label_1x_rx_left.setObjectName(_fromUtf8("label_1x_rx_left"))
        self.gridLayout.addWidget(self.label_1x_rx_left, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_1x_tx_total = QtGui.QLabel(self.tab)
        self.label_1x_tx_total.setObjectName(_fromUtf8("label_1x_tx_total"))
        self.gridLayout.addWidget(self.label_1x_tx_total, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 1, 2, 1, 1)
        self.label_1x_tx_left = QtGui.QLabel(self.tab)
        self.label_1x_tx_left.setObjectName(_fromUtf8("label_1x_tx_left"))
        self.gridLayout.addWidget(self.label_1x_tx_left, 1, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_2x_rx_total = QtGui.QLabel(self.tab)
        self.label_2x_rx_total.setObjectName(_fromUtf8("label_2x_rx_total"))
        self.gridLayout.addWidget(self.label_2x_rx_total, 2, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 2, 2, 1, 1)
        self.label_2x_rx_left = QtGui.QLabel(self.tab)
        self.label_2x_rx_left.setObjectName(_fromUtf8("label_2x_rx_left"))
        self.gridLayout.addWidget(self.label_2x_rx_left, 2, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_2x_tx_total = QtGui.QLabel(self.tab)
        self.label_2x_tx_total.setObjectName(_fromUtf8("label_2x_tx_total"))
        self.gridLayout.addWidget(self.label_2x_tx_total, 3, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 3, 2, 1, 1)
        self.label_2x_tx_left = QtGui.QLabel(self.tab)
        self.label_2x_tx_left.setObjectName(_fromUtf8("label_2x_tx_left"))
        self.gridLayout.addWidget(self.label_2x_tx_left, 3, 3, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 4, 0, 1, 1)
        self.label_mac_total = QtGui.QLabel(self.tab)
        self.label_mac_total.setObjectName(_fromUtf8("label_mac_total"))
        self.gridLayout.addWidget(self.label_mac_total, 4, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 4, 2, 1, 1)
        self.label_mac_left = QtGui.QLabel(self.tab)
        self.label_mac_left.setObjectName(_fromUtf8("label_mac_left"))
        self.gridLayout.addWidget(self.label_mac_left, 4, 3, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        spacerItem3 = QtGui.QSpacerItem(20, 33, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tableWidget = QtGui.QTableWidget(self.tab_2)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 751, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setIconSize(QtCore.QSize(20, 20))
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setRowCount(2)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 3, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(190)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(27)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.tableWidget_2 = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 70, 751, 301))
        self.tableWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_2.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_2.setRowCount(13)
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(9, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_2.setItem(9, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(10, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_2.setItem(10, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(11, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_2.setItem(11, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_2.setItem(12, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_2.setItem(12, 1, item)
        self.tableWidget_2.horizontalHeader().setVisible(False)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(23)
        self.radioButton_3 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_3.setGeometry(QtCore.QRect(160, 200, 89, 16))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButton_3)
        self.radioButton_4 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_4.setGeometry(QtCore.QRect(250, 200, 89, 16))
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.buttonGroup.addButton(self.radioButton_4)
        self.radioButton_5 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_5.setGeometry(QtCore.QRect(320, 190, 89, 16))
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.buttonGroup.addButton(self.radioButton_5)
        self.radioButton_6 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_6.setGeometry(QtCore.QRect(150, 260, 89, 16))
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.buttonGroup_2 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.radioButton_6)
        self.radioButton_7 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_7.setGeometry(QtCore.QRect(260, 260, 89, 16))
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.buttonGroup_2.addButton(self.radioButton_7)
        self.radioButton_8 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_8.setGeometry(QtCore.QRect(160, 290, 89, 16))
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.buttonGroup_3 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName(_fromUtf8("buttonGroup_3"))
        self.buttonGroup_3.addButton(self.radioButton_8)
        self.radioButton_9 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_9.setGeometry(QtCore.QRect(320, 290, 89, 16))
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.buttonGroup_3.addButton(self.radioButton_9)
        self.radioButton_10 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_10.setGeometry(QtCore.QRect(230, 290, 89, 16))
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.buttonGroup_3.addButton(self.radioButton_10)
        self.radioButton_11 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_11.setGeometry(QtCore.QRect(150, 380, 89, 16))
        self.radioButton_11.setObjectName(_fromUtf8("radioButton_11"))
        self.buttonGroup_4 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_4.setObjectName(_fromUtf8("buttonGroup_4"))
        self.buttonGroup_4.addButton(self.radioButton_11)
        self.radioButton_12 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_12.setGeometry(QtCore.QRect(150, 410, 89, 16))
        self.radioButton_12.setObjectName(_fromUtf8("radioButton_12"))
        self.buttonGroup_4.addButton(self.radioButton_12)
        self.radioButton_13 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_13.setGeometry(QtCore.QRect(150, 440, 89, 16))
        self.radioButton_13.setObjectName(_fromUtf8("radioButton_13"))
        self.buttonGroup_4.addButton(self.radioButton_13)
        self.radioButton_14 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_14.setGeometry(QtCore.QRect(150, 470, 89, 16))
        self.radioButton_14.setObjectName(_fromUtf8("radioButton_14"))
        self.buttonGroup_4.addButton(self.radioButton_14)
        self.radioButton_15 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_15.setGeometry(QtCore.QRect(330, 380, 89, 16))
        self.radioButton_15.setObjectName(_fromUtf8("radioButton_15"))
        self.buttonGroup_5 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_5.setObjectName(_fromUtf8("buttonGroup_5"))
        self.buttonGroup_5.addButton(self.radioButton_15)
        self.radioButton_17 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_17.setGeometry(QtCore.QRect(330, 440, 89, 16))
        self.radioButton_17.setObjectName(_fromUtf8("radioButton_17"))
        self.buttonGroup_5.addButton(self.radioButton_17)
        self.radioButton_16 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_16.setGeometry(QtCore.QRect(330, 410, 89, 16))
        self.radioButton_16.setObjectName(_fromUtf8("radioButton_16"))
        self.buttonGroup_5.addButton(self.radioButton_16)
        self.radioButton_18 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_18.setGeometry(QtCore.QRect(330, 470, 89, 16))
        self.radioButton_18.setObjectName(_fromUtf8("radioButton_18"))
        self.buttonGroup_5.addButton(self.radioButton_18)
        self.radioButton_19 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_19.setGeometry(QtCore.QRect(240, 430, 89, 16))
        self.radioButton_19.setObjectName(_fromUtf8("radioButton_19"))
        self.buttonGroup_6 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_6.setObjectName(_fromUtf8("buttonGroup_6"))
        self.buttonGroup_6.addButton(self.radioButton_19)
        self.radioButton_20 = QtGui.QRadioButton(self.tab_2)
        self.radioButton_20.setGeometry(QtCore.QRect(250, 460, 89, 16))
        self.radioButton_20.setObjectName(_fromUtf8("radioButton_20"))
        self.buttonGroup_6.addButton(self.radioButton_20)
        self.comboBox = QtGui.QComboBox(self.tab_2)
        self.comboBox.setGeometry(QtCore.QRect(410, 450, 69, 22))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.tableWidget_3 = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 380, 751, 41))
        self.tableWidget_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_3.setRowCount(2)
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_3.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_3.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_3.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidget_3.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_3.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_3.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_3.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget_3.setItem(1, 3, item)
        self.tableWidget_3.horizontalHeader().setVisible(False)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.tableWidget_3.verticalHeader().setDefaultSectionSize(20)
        self.layoutWidget = QtGui.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 490, 741, 91))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.file_edit_2 = QtGui.QLineEdit(self.layoutWidget)
        self.file_edit_2.setObjectName(_fromUtf8("file_edit_2"))
        self.horizontalLayout_3.addWidget(self.file_edit_2)
        self.pushButton_3 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_3.setAutoExclusive(True)
        self.pushButton_3.setAutoDefault(True)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.file_edit_3 = QtGui.QLineEdit(self.layoutWidget)
        self.file_edit_3.setObjectName(_fromUtf8("file_edit_3"))
        self.horizontalLayout_4.addWidget(self.file_edit_3)
        self.pushButton_4 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_4.setAutoExclusive(True)
        self.pushButton_4.setAutoDefault(True)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.pushButton_5 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_8.addWidget(self.pushButton_5)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(30, 200, 54, 12))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.line = QtGui.QFrame(self.tab_3)
        self.line.setGeometry(QtCore.QRect(370, 0, 20, 581))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_35 = QtGui.QLabel(self.tab_3)
        self.label_35.setGeometry(QtCore.QRect(400, 200, 54, 12))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.pushButton_6 = QtGui.QPushButton(self.tab_3)
        self.pushButton_6.setGeometry(QtCore.QRect(210, 30, 75, 23))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(210, 100, 75, 23))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(self.tab_3)
        self.pushButton_8.setGeometry(QtCore.QRect(630, 83, 75, 23))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.tab_3)
        self.textBrowser_2.setGeometry(QtCore.QRect(30, 220, 331, 241))
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.textBrowser_3 = QtGui.QTextBrowser(self.tab_3)
        self.textBrowser_3.setGeometry(QtCore.QRect(400, 220, 331, 241))
        self.textBrowser_3.setObjectName(_fromUtf8("textBrowser_3"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(400, 30, 191, 91))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_27 = QtGui.QLabel(self.layoutWidget1)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_5.addWidget(self.label_27, 0, 0, 1, 1)
        self.comboBox_7 = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_7.setEditable(True)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.gridLayout_5.addWidget(self.comboBox_7, 1, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.layoutWidget1)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_5.addWidget(self.label_29, 1, 0, 1, 1)
        self.label_28 = QtGui.QLabel(self.layoutWidget1)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_5.addWidget(self.label_28, 2, 0, 1, 1)
        self.comboBox_8 = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_8.setEditable(True)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.gridLayout_5.addWidget(self.comboBox_8, 2, 1, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout_5.addWidget(self.lineEdit_7, 0, 1, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(self.tab_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(32, 80, 151, 41))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_24 = QtGui.QLabel(self.layoutWidget2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_5.addWidget(self.label_24)
        self.lineEdit_12 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.horizontalLayout_5.addWidget(self.lineEdit_12)
        self.label_33 = QtGui.QLabel(self.layoutWidget2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_5.addWidget(self.label_33)
        self.lineEdit_4 = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_5.addWidget(self.lineEdit_4)
        self.layoutWidget3 = QtGui.QWidget(self.tab_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(33, 130, 151, 51))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_26 = QtGui.QLabel(self.layoutWidget3)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_7.addWidget(self.label_26)
        self.lineEdit_6 = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_7.addWidget(self.lineEdit_6)
        self.label_36 = QtGui.QLabel(self.layoutWidget3)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_7.addWidget(self.label_36)
        self.lineEdit_11 = QtGui.QLineEdit(self.layoutWidget3)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.horizontalLayout_7.addWidget(self.lineEdit_11)
        self.layoutWidget4 = QtGui.QWidget(self.tab_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(31, 21, 151, 61))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_3 = QtGui.QLabel(self.layoutWidget4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.layoutWidget4)
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.gridLayout_3.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.comboBox_6 = QtGui.QComboBox(self.layoutWidget4)
        self.comboBox_6.setEditable(True)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.gridLayout_3.addWidget(self.comboBox_6, 1, 1, 1, 1)
        self.layoutWidget5 = QtGui.QWidget(self.tab_3)
        self.layoutWidget5.setGeometry(QtCore.QRect(400, 120, 242, 71))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_30 = QtGui.QLabel(self.layoutWidget5)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_6.addWidget(self.label_30)
        self.dateEdit_2 = QtGui.QDateEdit(self.layoutWidget5)
        self.dateEdit_2.setObjectName(_fromUtf8("dateEdit_2"))
        self.horizontalLayout_6.addWidget(self.dateEdit_2)
        self.label_37 = QtGui.QLabel(self.layoutWidget5)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_6.addWidget(self.label_37)
        self.dateEdit = QtGui.QDateEdit(self.layoutWidget5)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_6.addWidget(self.dateEdit)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.textBrowser = QtGui.QTextBrowser(self.tab_4)
        self.textBrowser.setGeometry(QtCore.QRect(30, 30, 331, 471))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.line_2 = QtGui.QFrame(self.tab_4)
        self.line_2.setGeometry(QtCore.QRect(370, 0, 20, 581))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.pushButton_10 = QtGui.QPushButton(self.tab_4)
        self.pushButton_10.setGeometry(QtCore.QRect(450, 190, 75, 23))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.layoutWidget6 = QtGui.QWidget(self.tab_4)
        self.layoutWidget6.setGeometry(QtCore.QRect(450, 63, 201, 101))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_31 = QtGui.QLabel(self.layoutWidget6)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 0, 0, 1, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_2.addWidget(self.lineEdit_8, 0, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.layoutWidget6)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_2.addWidget(self.label_32, 1, 0, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout_2.addWidget(self.lineEdit_9, 1, 1, 1, 1)
        self.label_34 = QtGui.QLabel(self.layoutWidget6)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_2.addWidget(self.label_34, 2, 0, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout_2.addWidget(self.lineEdit_10, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 690, 781, 20))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 825, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menuBar)
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_3 = QtGui.QAction(MainWindow)
        self.action_3.setObjectName(_fromUtf8("action_3"))
        self.action222 = QtGui.QAction(MainWindow)
        self.action222.setObjectName(_fromUtf8("action222"))
        self.action_2 = QtGui.QAction(MainWindow)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.menu.addAction(self.action)
        self.menu.addSeparator()
        self.menu.addAction(self.action_3)
        self.menu.addSeparator()
        self.menuBar.addAction(self.menu.menuAction())
        self.label.setBuddy(self.macEdit)
        self.label_69.setBuddy(self.radioButton)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow._import_mac)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.choose_file_2)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.choose_file_3)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.export_bin)
        QtCore.QObject.connect(self.pushButton_6, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.search_lot)
        QtCore.QObject.connect(self.pushButton_7, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.search_key)
        QtCore.QObject.connect(self.pushButton_8, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.search_by_keyword)
        QtCore.QObject.connect(self.pushButton_10, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.retrieve_key)
        QtCore.QObject.connect(self.pushButton_9, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.choose_file)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.import_bin)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "输入Mac前缀", None))
        self.pushButton.setText(_translate("MainWindow", "开始导入", None))
        self.pushButton_9.setText(_translate("MainWindow", "导入bin文件", None))
        self.pushButton_2.setText(_translate("MainWindow", "开始导入", None))
        self.label_69.setText(_translate("MainWindow", "key 版本", None))
        self.radioButton.setText(_translate("MainWindow", "1.x", None))
        self.radioButton_2.setText(_translate("MainWindow", "2.x", None))
        self.label_5.setText(_translate("MainWindow", "1x_rx 总数", None))
        self.label_1x_rx_total.setText(_translate("MainWindow", "0", None))
        self.label_13.setText(_translate("MainWindow", "剩余", None))
        self.label_1x_rx_left.setText(_translate("MainWindow", "0", None))
        self.label_6.setText(_translate("MainWindow", "1x_tx 总数", None))
        self.label_1x_tx_total.setText(_translate("MainWindow", "0", None))
        self.label_14.setText(_translate("MainWindow", "剩余", None))
        self.label_1x_tx_left.setText(_translate("MainWindow", "0", None))
        self.label_7.setText(_translate("MainWindow", "2x_rx 总数", None))
        self.label_2x_rx_total.setText(_translate("MainWindow", "0", None))
        self.label_15.setText(_translate("MainWindow", "剩余", None))
        self.label_2x_rx_left.setText(_translate("MainWindow", "0", None))
        self.label_8.setText(_translate("MainWindow", "2x_tx 总数", None))
        self.label_2x_tx_total.setText(_translate("MainWindow", "0", None))
        self.label_16.setText(_translate("MainWindow", "剩余", None))
        self.label_2x_tx_left.setText(_translate("MainWindow", "0", None))
        self.label_22.setText(_translate("MainWindow", "mac 总数", None))
        self.label_mac_total.setText(_translate("MainWindow", "0", None))
        self.label_25.setText(_translate("MainWindow", "剩余", None))
        self.label_mac_left.setText(_translate("MainWindow", "0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "导入key", None))
        self.tableWidget.setSortingEnabled(True)
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "申请日期", None))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "所属人员", None))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "申请部门", None))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "此处待定", None))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("MainWindow", "调用类型", None))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("MainWindow", "key来源", None))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("MainWindow", "key内容", None))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("MainWindow", "key版本/类型", None))
        item = self.tableWidget_2.item(3, 1)
        item.setText(_translate("MainWindow", "TX", None))
        item = self.tableWidget_2.item(3, 3)
        item.setText(_translate("MainWindow", "RX", None))
        item = self.tableWidget_2.item(7, 0)
        item.setText(_translate("MainWindow", "有无内部型号", None))
        item = self.tableWidget_2.item(9, 0)
        item.setText(_translate("MainWindow", "需求片数", None))
        item = self.tableWidget_2.item(10, 0)
        item.setText(_translate("MainWindow", "需求key数", None))
        item = self.tableWidget_2.item(11, 0)
        item.setText(_translate("MainWindow", "单位", None))
        item = self.tableWidget_2.item(12, 0)
        item.setText(_translate("MainWindow", "测试工程师", None))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.radioButton_3.setText(_translate("MainWindow", "工程", None))
        self.radioButton_4.setText(_translate("MainWindow", "量产", None))
        self.radioButton_5.setText(_translate("MainWindow", "pilot run", None))
        self.radioButton_6.setText(_translate("MainWindow", "Availink", None))
        self.radioButton_7.setText(_translate("MainWindow", "customer", None))
        self.radioButton_8.setText(_translate("MainWindow", "16进制", None))
        self.radioButton_9.setText(_translate("MainWindow", "2进制", None))
        self.radioButton_10.setText(_translate("MainWindow", "8进制", None))
        self.radioButton_11.setText(_translate("MainWindow", "1.X", None))
        self.radioButton_12.setText(_translate("MainWindow", "2.X", None))
        self.radioButton_13.setText(_translate("MainWindow", "Both", None))
        self.radioButton_14.setText(_translate("MainWindow", "None", None))
        self.radioButton_15.setText(_translate("MainWindow", "1.X", None))
        self.radioButton_17.setText(_translate("MainWindow", "Both", None))
        self.radioButton_16.setText(_translate("MainWindow", "2.X", None))
        self.radioButton_18.setText(_translate("MainWindow", "None", None))
        self.radioButton_19.setText(_translate("MainWindow", "有内部型号", None))
        self.radioButton_20.setText(_translate("MainWindow", "无内部型号", None))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.item(0, 0)
        item.setText(_translate("MainWindow", "序号", None))
        item = self.tableWidget_3.item(0, 1)
        item.setText(_translate("MainWindow", "外包商", None))
        item = self.tableWidget_3.item(0, 2)
        item.setText(_translate("MainWindow", "批号", None))
        item = self.tableWidget_3.item(0, 3)
        item.setText(_translate("MainWindow", "片号", None))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.pushButton_3.setText(_translate("MainWindow", "载入表格", None))
        self.pushButton_4.setText(_translate("MainWindow", "导出目录", None))
        self.pushButton_5.setText(_translate("MainWindow", "开始导出", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "导出key", None))
        self.label_2.setText(_translate("MainWindow", "查询结果", None))
        self.label_35.setText(_translate("MainWindow", "查询结果", None))
        self.pushButton_6.setText(_translate("MainWindow", "查询 lot", None))
        self.pushButton_7.setText(_translate("MainWindow", "查询 key", None))
        self.pushButton_8.setText(_translate("MainWindow", "查询", None))
        self.label_27.setText(_translate("MainWindow", "用户", None))
        self.label_29.setText(_translate("MainWindow", "操作类型", None))
        self.label_28.setText(_translate("MainWindow", "内部型号", None))
        self.label_24.setText(_translate("MainWindow", "X 坐标", None))
        self.label_33.setText(_translate("MainWindow", "-", None))
        self.label_26.setText(_translate("MainWindow", "Y 坐标", None))
        self.label_36.setText(_translate("MainWindow", "-", None))
        self.label_3.setText(_translate("MainWindow", "Lot ID ", None))
        self.label_4.setText(_translate("MainWindow", "Wafer ID", None))
        self.label_30.setText(_translate("MainWindow", "日期", None))
        self.label_37.setText(_translate("MainWindow", "-", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "查询", None))
        self.pushButton_10.setText(_translate("MainWindow", "回收", None))
        self.label_31.setText(_translate("MainWindow", "管理员密码", None))
        self.label_32.setText(_translate("MainWindow", "Lot ID", None))
        self.label_34.setText(_translate("MainWindow", "再输入一次", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "历史/回收", None))
        self.menu.setTitle(_translate("MainWindow", "用户管理", None))
        self.action.setText(_translate("MainWindow", "添加/删除用户", None))
        self.action_3.setText(_translate("MainWindow", "修改密码", None))
        self.action222.setText(_translate("MainWindow", "222", None))
        self.action_2.setText(_translate("MainWindow", "啊", None))

